services:
  mcpsrv:
    container_name: zena_mcp_
    build: .
    image: zena_mcp_:latest
    env_file:
      - .env
    ports:
      - "4011:4011"
      - "4012:4012"
      - "4015:4015"
      - "4016:4016"
      - "4017:4017"
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    restart: unless-stopped