services:
  mcpsrv:
    container_name: zena_mcp_local
    build: .
    image: zena_mcp_local:latest
    env_file:
      - ../deploy/dev.env
    ports:
      - "15001:15001"
      - "15002:15002"
      - "15005:15005"
      - "15006:15006"
      - "15007:15007"
      - "15017:15017"
      - "15018:15018"
      - "15020:15020"
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    restart: unless-stopped