services:
  mcpsrv:
    build: .
    env_file:
      - .env
    ports:
      - "4011:4011"
      - "4012:4012"
      - "4015:4015"
      - "4016:4016"
      - "4017:4017"
    volumes:
      - .:/app  # монтируем код, чтобы изменения влияли сразу
    restart: unless-stopped


# docker-compose down           # Остановить и удалить старый контейнер и сеть
# docker-compose up --build -d  # С пересборкой и запуском в фоне

# cd /home/copilot_superuser/petrunin/zena/mcpserver
# docker-compose logs -f mcpsrv

# apt update && apt install -y curl
