services:
  mcpsrv:
    build: .
    env_file:
      - .env
    ports:
      - "4011:4011"
      - "4012:4012"
    volumes:
      - .:/app
    restart: unless-stopped

# docker-compose down           # Остановить и удалить старый контейнер и сеть
# docker-compose up --build -d  # С пересборкой и запуском в фоне