services:
  mcpsrv:
    container_name: zena_mcp
    build: .
    image: zena_mcp:latest
    env_file:
      - .env
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5005:5005"
      - "5006:5006"
      - "5007:5007"
      - "5017:5017"
      - "5018:5018"
      - "5020:5020"
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    restart: unless-stopped
    networks:
      - zena-network
